nothing:
	@echo "Say 'make docker' if you want to build a docker image."
	@echo "(You shouldn't need to, though: just say "
	@echo "  docker run -ti rgrig/ukc-co663-depsolver"
	@echo "to use the pre-built one.)"

docker:
	docker build -t ukc-co663-depsolver .
